config/routes.rb
Rails.application.routes.draw do
  resources :gopis

  root 'gopis#index'

  resources :gopis

end

app/models/gopi.rb
class Gopi < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gopis_controller.rb
class GopisController < ApplicationController
  before_action :set_gopi, only: [:show, :edit, :update, :destroy]

  # GET /gopis
  # GET /gopis.json
  def index
    @gopis = Gopi.all
  end

  # GET /gopis/1
  # GET /gopis/1.json
  def show
  end

  # GET /gopis/new
  def new
    @gopi = Gopi.new
  end

  # GET /gopis/1/edit
  def edit
  end

  # POST /gopis
  # POST /gopis.json
  def create
    @gopi = Gopi.new(gopi_params)

    respond_to do |format|
      if @gopi.save
        ExampleMailer.sample_email(@gopi).deliver
        format.html { redirect_to @gopi, notice: 'Gopi was successfully created.' }
        format.json { render :show, status: :created, location: @gopi }
      else
        format.html { render :new }
        format.json { render json: @gopi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gopis/1
  # PATCH/PUT /gopis/1.json
  def update
    respond_to do |format|
      if @gopi.update(gopi_params)
        format.html { redirect_to @gopi, notice: 'Gopi was successfully updated.' }
        format.json { render :show, status: :ok, location: @gopi }
      else
        format.html { render :edit }
        format.json { render json: @gopi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gopis/1
  # DELETE /gopis/1.json
  def destroy
    @gopi.destroy
    respond_to do |format|
      format.html { redirect_to gopis_url, notice: 'Gopi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gopi
      @gopi = Gopi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gopi_params
      params.require(:gopi).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gopis_helper.rb
module GopisHelper
end

app/views/gopis/_form.html.erb
<%= form_for(@gopi) do |f| %>
  <% if @gopi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gopi.errors.count, "error") %> prohibited this gopi from being saved:</h2>

      <ul>
      <% @gopi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gopis/edit.html.erb
<h1>Editing Gopi</h1>

<%= render 'form' %>

<%= link_to 'Show', @gopi %> |
<%= link_to 'Back', gopis_path %>

app/views/gopis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gopis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gopis.each do |gopi| %>
      <tr>
        <td><%= gopi.name %></td>
        <td><%= gopi.email %></td>
        <td><%= link_to 'Show', gopi %></td>
        <td><%= link_to 'Edit', edit_gopi_path(gopi) %></td>
        <td><%= link_to 'Destroy', gopi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gopi', new_gopi_path %>

app/views/gopis/new.html.erb
<h1>New Gopi</h1>

<%= render 'form' %>

<%= link_to 'Back', gopis_path %>

app/views/gopis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gopi.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @gopi.email %>
</p>

<%= link_to 'Edit', edit_gopi_path(@gopi) %> |
<%= link_to 'Back', gopis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Email</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>